platform:
  - x64
  - x86
build_script:
  - if "%platform%" == "x86" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%platform%" == "x64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%platform%" == "x64" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - cd win32
  - cscript configure.js compiler=msvc iconv=no prefix=c:\opt include=c:\opt\include lib=c:\opt\lib debug=yes
  - nmake /f Makefile.msvc
  - del ..\test\ebcdic*.xml
  - nmake /f Makefile.msvc checktests
